services:
  tg-proxy-tunnel:
    image: ubuntu/squid:latest
    container_name: tg_proxy_tunnel
    restart: always
    command: >
      sh -c "echo 'cache_peer round-sea-bc13.yanik22801.workers.dev parent 443 0 no-query default ssl' >> /etc/squid/squid.conf &&
             echo 'http_access allow all' >> /etc/squid/squid.conf &&
             echo 'never_direct allow all' >> /etc/squid/squid.conf &&
             squid -N"

  telegram-api-server:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram_api_server
    ports:
      - "8081:8081"
    volumes:
      - tg_shared_data:/var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_LOCAL=True
      - http_proxy=http://tg-proxy-tunnel:3128
      - https_proxy=http://tg-proxy-tunnel:3128
    depends_on:
      - tg-proxy-tunnel
    restart: always

  tg-bot:
    build: .
    container_name: typescript_tg_bot
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      telegram-api-server:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - tg_shared_data:/var/lib/telegram-bot-api
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  tg_shared_data:
  db-data:
