name: bot deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node:24-apline
      - run: npm install
      - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: compose up
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd tg_bot2
            git pull
            docker compose up -d --build
